security:
  basic:
    enabled: false
spring:
  datasource:
    state:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/wonderbox
      username: poc
      password: poc
      validationQuery: SELECT 1
      testOnBorrow: true
      initial-size: 1
      min-idle: 1
  jpa:
    hibernate:
      ddl-auto: create-drop

hibernate:
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: false
  ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  order_inserts: true
  order_updates: true
  jdbc.batch_size: 30
  hbm2ddl.auto: create-drop


